# Application name Configuration
spring.application.name=UniversityManagementSystem

# Server port Configuration
server.port=8080

# Set the Context path
server.servlet.context-path=/ums

#Active the local profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local} 
# This will default to 'local' if SPRING_PROFILES_ACTIVE is not set in the environment

# Set the database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/UniversityManagementSystem
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
